ToDo/ToDo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('desk/', include('desk.urls')),
    path('users/', include('users.urls')),
]

ToDo/desk/urls.py
from django.urls import path

from . import views

app_name = 'desk'
urlpatterns = [
    path('projects/create', views.ProjectCreateView.as_view(), name='project_create'),
    path('projects/', views.ProjectListView.as_view(), name='project_list'),
    path('projects/update/<int:pk>', views.ProjectUpdateView.as_view(), name='project_update'),
    path('projects/delete/<int:pk>', views.ProjectDeleteView.as_view(), name='project_delete'),

    path('tasks/create', views.TaskCreateView.as_view(), name='task_create'),
    path('tasks/update/<int:pk>', views.TaskUpdateView.as_view(), name='task_update'),
    path('tasks/delete/<int:pk>', views.TaskDeleteView.as_view(), name='task_delete'),

    path('task/complete/<int:pk>', views.complete_task, name='task_complete'),

    path('set-timezone', views.set_timezone, name='set_timezone'),
]

ToDo/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
    path('register', views.register, name='register'),
    path('login', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile', views.profile, name='profile'),
]

ToDo/desk/models.py
from django.db.models import Model, ForeignKey, CASCADE
from django.db.models.fields import CharField, DateTimeField, TextField, SmallIntegerField
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone


class Project(Model):
    name = CharField(max_length=50)
    user = ForeignKey(User, on_delete=CASCADE)

    def __str__(self):
        return self.name

    @staticmethod
    def get_absolute_url():
        return reverse('desk:project_list')


class Task(Model):
    STATUS = ((0, 'new'),
              (1, 'in_progress'),
              (2, 'wasted'),
              (3, 'done'))

    title = CharField(max_length=70)
    description = TextField()
    date_created = DateTimeField('date_created')
    deadline = DateTimeField('deadline', null=True, blank=True)
    status = SmallIntegerField(choices=STATUS, default=0)
    project = ForeignKey(Project, on_delete=CASCADE)

    def __str__(self):
        return f'{self.title}, created: {self.date_created}'

    def update_status(self):
        if self.status != 3:  # if status is not done -- check for update
            if self.deadline and self.status == 0:
                print('case_1')
                self.status = 1
                self.save()
            elif not self.deadline and self.status != 0:
                print('case_2')
                self.status = 0
                self.save()
            elif self.deadline:
                timedelta = self.deadline - timezone.now()
                if timedelta.days < 0 and self.status != 2:
                    print('case_3')
                    self.status = 2
                    self.save()
                elif timedelta.days >= 0 and self.status != 1:
                    print('case_4')
                    self.status = 1
                    self.save()
            return self.get_time_to_deadline()
        else:
            return None

    def get_time_to_deadline(self):
        """
        Func returns time to deadline as a string.
        """
        timedelta = self.deadline - timezone.now()
        if timedelta.days < 0:
            return f'0 seconds'
        elif timedelta.days >= 1:
            return f'{timedelta.days} days'
        elif timedelta.days <= 0 and timedelta.seconds > 3600:  # more than an hour
            return f'{timedelta.seconds // 3600} hours'
        elif timedelta.seconds < 3600:
            return f'{timedelta.seconds // 60} minutes'
        elif timedelta.seconds < 60:
            return f'{timedelta.seconds} seconds'

    @staticmethod
    def get_absolute_url():
        return reverse('desk:project_list')

ToDo/desk/forms.py
from django import forms
from django.utils import timezone
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Fieldset, Field, Submit, Row, HTML

from .models import Project, Task

CONTAINER_CSS_CLASS = 'm-auto w-50 border rounded text-center p-3 text-white'
FIELDSET_CSS_CLASS = 'form-group'
FIELD_CSS_CLASS = 'bg-dark text-white border-light text-left'
BUTTON_CSS_CLASS = 'btn btn-dark border-light'
ROW_BUTTON_HOLDER = 'w-50 m-auto d-flex justify-content-around'
ROW_JUSTIFY_CONTENT_AROUND = 'd-flex justify-content-around'
CANCEL_HYPERLINK_HTML = "<a class='btn btn-dark' href='{% url 'desk:project_list' %}'>Cancel</a>"


class ProjectForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        """
        Arguments: button_label, form_legend are obtained from views across a get_form_kwargs function.
        """
        self.button_label = kwargs.pop('button_label')
        self.form_legend = kwargs.pop('form_legend')
        super(ProjectForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            Div(
                Fieldset(
                    self.form_legend,  # 1th arg -- form legend
                    Field('name', css_class=FIELD_CSS_CLASS, autocomplete='off'),
                    css_class=FIELDSET_CSS_CLASS
                ),
                Row(
                    Submit('submit', self.button_label, css_class=BUTTON_CSS_CLASS),
                    HTML(CANCEL_HYPERLINK_HTML),
                    css_class=ROW_BUTTON_HOLDER
                ),
                css_class=CONTAINER_CSS_CLASS
            )
        )

    class Meta:
        model = Project
        fields = ('name', )


class TaskForm(forms.ModelForm):
    """
    Arguments: button_label, form_legend, user(current user) are obtained from views across a get_form_kwargs function.
    """
    def __init__(self, *args, **kwargs):
        self.button_label = kwargs.pop('button_label')
        self.form_legend = kwargs.pop('form_legend')
        self.user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['project'].queryset = Project.objects.filter(user=self.user)
        self.fields['date_created'] = forms.DateTimeField(initial=timezone.now)

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                Fieldset(
                    self.form_legend,  # 1th arg -- form legend
                    Field('title', css_class=FIELD_CSS_CLASS, autocomplete='off'),
                    Field('description', css_class=FIELD_CSS_CLASS, autocomplete='off'),
                    Row(
                        Field('date_created', css_class=FIELD_CSS_CLASS),
                        Field('deadline', css_class=FIELD_CSS_CLASS),
                        css_class=ROW_JUSTIFY_CONTENT_AROUND
                    ),
                    Field('project', css_class=FIELD_CSS_CLASS),
                    css_class=FIELDSET_CSS_CLASS
                ),
                Row(
                    Submit('submit', self.button_label, css_class=BUTTON_CSS_CLASS),
                    HTML(CANCEL_HYPERLINK_HTML),
                    css_class=ROW_BUTTON_HOLDER
                ),
                css_class=CONTAINER_CSS_CLASS
            )
        )

    class Meta:
        model = Task
        fields = ('title', 'description', 'date_created', 'deadline', 'project')

ToDo/desk/views.py
import pytz
from django.core.exceptions import PermissionDenied
from django.views import generic
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required

from .models import Project, Task
from .forms import ProjectForm, TaskForm


def set_timezone(request):
    if request.method == 'POST':
        request.session['django_timezone'] = request.POST['timezone']
        return redirect('desk:project_list')
    else:
        return render(request, 'desk/tz_template.html', {'timezones': pytz.common_timezones})


class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
    model = Project
    form_class = ProjectForm
    template_name = 'desk/form.html'
    extra_context = {'title': 'Project Create'}

    def get_form_kwargs(self):
        """
        Function to send extra args to the form
        """
        kwargs = super().get_form_kwargs()
        kwargs['button_label'] = 'Create'
        kwargs['form_legend'] = 'Enter a name for the new project'
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ProjectListView(LoginRequiredMixin, generic.ListView):
    model = Project
    extra_context = {'title': 'Projects List'}

    def get_queryset(self):
        return Project.objects.filter(user=self.request.user)


class ProjectUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Project
    form_class = ProjectForm
    template_name = 'desk/form.html'
    extra_context = {'title': 'Project Update'}

    def get_form_kwargs(self):
        """
        Function to send extra args to the form
        """
        kwargs = super().get_form_kwargs()
        kwargs['button_label'] = 'Update'
        kwargs['form_legend'] = 'Enter new name for the project'
        return kwargs

    def test_func(self):
        project = self.get_object()
        if self.request.user == project.user:
            return True
        else:
            return False


class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Project
    success_url = reverse_lazy('desk:project_list')

    def test_func(self):
        project = self.get_object()
        if self.request.user == project.user:
            return True
        else:
            return False


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'desk/form.html'
    extra_context = {'title': 'Task Create'}

    def get_form_kwargs(self):
        """
        Function to send extra args to the form
        """
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['button_label'] = 'Create'
        kwargs['form_legend'] = 'Creating Task Form.'
        return kwargs

    def form_valid(self, form):
        if form.instance.project.user == self.request.user:
            return super().form_valid(form)
        else:
            raise PermissionDenied


class TaskUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'desk/form.html'
    extra_context = {'title': 'Task Update'}

    def get_form_kwargs(self):
        """
        Function to send extra args to the form
        """
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['button_label'] = 'Update'
        kwargs['form_legend'] = 'Updating Task Form.'
        return kwargs

    def test_func(self):
        task = self.get_object()
        project = task.project
        if self.request.user == project.user:
            return True
        else:
            return False


class TaskDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy('desk:project_list')

    def test_func(self):
        task = self.get_object()
        project = task.project
        if self.request.user == project.user:
            return True
        else:
            return False


@login_required
def complete_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.status = 3
    task.save()
    messages.success(request, f'Task has been marked as done.')
    return redirect('desk:project_list')

ToDo/desk/templates/desk/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>ToDo-{{ title }}</title>
    {% else %}
        <title>ToDo</title>
    {% endif %}

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body class="bg-dark">

    <header>
        <nav class="navbar navbar-expand-md navbar-dark">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'desk:project_list' %}">ToDo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="text-white m-auto">
                        {% if user.is_authenticated %}
                            <h5><a href="{% url 'desk:project_list' %}" class="text-white">{{ user.username }}'s desk</a></h5>
                        {% endif %}
                    </div>
                <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a>
                            <a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
                            <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>


<!--    alert messages-->
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
<!--    end of alert messages-->


    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

ToDo/desk/templates/desk/form.html
{% extends "desk/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {% crispy form %}
{% endblock content %}

ToDo/desk/templates/desk/project_confirm_delete.html
{% extends 'desk/base.html' %}
{% block content %}
    <div class="m-auto w-50 border rounded text-center p-2">
        <form method="post" class="form-group text-white">
            {% csrf_token %}
            <h2>Are you sure you want to delete project: "{{ object }}"?</h2>
            <p>WARNING! Deleting the project will also delete ALL project related tasks.</p>
            <span class="w-50 m-auto d-flex justify-content-around">
                <input class="btn btn-danger" type="submit" value="Confirm">
                <a class="btn btn-dark" href="{% url 'desk:project_list' %}">Cancel</a>
            </span>
        </form>
    </div>

{% endblock content %}

ToDo/desk/templates/desk/project_list.html
{% extends 'desk/base.html' %}
{% load static %}

{% block content %}

<!--LEFT SIDE-->
<div class="row" style="height: 75vh">
    <div class="col-3 border rounded p-0">
        <div class="border rounded m-1 p-2 text-center text-white position-relative">
            <span>Projects</span>
            <a href="{% url 'desk:project_create' %}" class="float-right stretched-link" data-toggle="tooltip" data-placement="right" title="Create a project">
                <img src="{% static 'desk/icons/create-16.png' %}" alt="C">
            </a>
        </div>
        <div class="border rounded m-1">
            <div id="project-btn-group" class="btn-group-vertical d-block">
<!--                generate project list-->
               {% for project in project_list %}
                    <button class="btn btn-dark" type="button" data-toggle="collapse" data-target="#collapse-{{ project.id }}"  aria-expanded="false" aria-controls="collapse-{{ project.id }}">
                        {{ project }}
                        <span class="float-right">
                            <a href="{% url 'desk:project_update' project.id %}" data-toggle="tooltip" data-placement="right" title="Edit the project">
                                <img src="{% static 'desk/icons/edit-16.png' %}" alt="U">
                            </a>
                            <a href="{% url 'desk:project_delete' project.id %}" data-toggle="tooltip" data-placement="right" title="Delete the project">
                                <img src="{% static 'desk/icons/delete-16.png' %}" alt="D">
                            </a>
                        </span>
                    </button>
                {% endfor %}
            </div>
        </div>
    </div>
<!--RIGHT SIDE-->
    <div id="task-area" class="col-9 border rounded p-1">
        <div class="border rounded p-2 mb-1 text-center text-white position-relative">
            <span>Tasks</span>
            <a href="{% url 'desk:task_create' %}" class="float-right stretched-link" data-toggle="tooltip" data-placement="right" title="Create a task">
                <img src="{% static 'desk/icons/create-16.png' %}" alt="C">
            </a>
        </div>
        {% for project in project_list %}
            <div id="collapse-{{ project.id }}" class="collapse rounded bg-dark text-white" data-parent="#task-area">
                <div class="card card-body bg-dark border-light btn-group-vertical p-0">
<!--                        generate task list-->
                    {% if project.task_set.all %}
                        {% for task in project.task_set.all %}
                            <button class="btn btn-dark text-left" type="button" data-toggle="collapse" data-target="#collapse-task-{{ task.id }}" aria-expanded="false" aria-controls="collapse-task-{{ task.id }}">

<!--                                badges-->
                                {% if task.status == 0 %}
                                    <span class="badge badge-secondary col-1">new</span>
                                {% elif task.status == 1 %}
                                    <span class="badge badge-info col-1">working</span>
                                {% elif task.status == 2 %}
                                    <span class="badge badge-danger col-1">wasted</span>
                                {% elif task.status == 3 %}
                                    <span class="badge badge-success col-1">done</span>
                                {% endif %}
<!--                                end badges-->

                                <span class=>{{ task.title }}</span>
                                <span class="float-right">

<!--                                    deadline-->
                                    {% if task.deadline and task.status != 3 %}
                                        <span class="mr-2">Deadline in: {{ task.update_status }}</span>
                                    {% endif %}
<!--                                    end deadline-->

                                    <a href="{% url 'desk:task_update' task.id %}" data-toggle="tooltip" data-placement="right" title="Edit the task">
                                        <img src="{% static 'desk/icons/edit-16.png' %}" alt="U">
                                    </a>
                                    <a href="{% url 'desk:task_delete' task.id %}" data-toggle="tooltip" data-placement="right" title="Delete the task">
                                        <img src="{% static 'desk/icons/delete-16.png' %}" alt="D">
                                    </a>
                                </span>
                            </button>
                        {% endfor %}
                    {% else %}
                        <p class="pt-2 pl-2">There no tasks yet.</p>
                    {% endif %}
<!--                       end generate task list-->
                </div>
            </div>

<!--                generate task detail-->
            {% if project.task_set.all %}
                {% for task in project.task_set.all %}
                    <div id="collapse-task-{{ task.id }}" class="collapse rounded bg-dark text-white" data-parent="#task-area">
                        <div class="card card-body bg-dark border-light">
                            <p class="row">
                                <span class="col-2">Tittle: </span>{{ task.title }}
                                <span class="ml-auto mr-2">
                                    <a href="{% url 'desk:task_update' task.id %}" data-toggle="tooltip" data-placement="right" title="Edit the task">
                                        <img src="{% static 'desk/icons/edit-16.png' %}" alt="U">
                                    </a>
                                    <a href="{% url 'desk:task_delete' task.id %}" data-toggle="tooltip" data-placement="right" title="Delete the task">
                                        <img src="{% static 'desk/icons/delete-16.png' %}" alt="D">
                                    </a>
                                </span>
                            </p>
                            <p class="row"><span class="col-2">Status: </span>

<!--                                badges-->
                                {% if task.status == 0 %}
                                    <span class="badge badge-secondary col-1">new</span>
                                {% elif task.status == 1 %}
                                    <span class="badge badge-info col-1">working</span>
                                {% elif task.status == 2 %}
                                    <span class="badge badge-danger col-1">wasted</span>
                                {% elif task.status == 3 %}
                                    <span class="badge badge-success col-1">done</span>
                                {% endif %}
                            </p>
<!--                                end badges-->

                            <p class="row"><span class="col-2">Created: </span>{{ task.date_created }}</p>

                            <p class="row"><span class="col-2">Deadline: </span>
                                {% if task.deadline and task.status != 3 %}
                                    {{ task.deadline }} ({{ task.update_status }})
                                {% elif task.deadline and task.status == 3 %}
                                    {{ task.deadline }}
                                {% else  %}
                                    not defined
                                {% endif %}
                            </p>

                            <p>Description: </p>
                            <p>{{ task.description }}</p>
                            <div class="row m-auto">
                                {% if task.status == 0 or task.status == 1 %}
                                    <a href="{% url 'desk:task_complete' task.id %}" class="btn btn-success">Mark as done</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
<!--               end generate task detail-->

        {% endfor %}
    </div>

</div>

{% endblock content %}

ToDo/desk/templates/desk/task_confirm_delete.html
{% extends 'desk/base.html' %}
{% block content %}
    <div class="m-auto w-50 border rounded text-center p-2">
        <form method="post" class="form-group text-white">
            {% csrf_token %}
            <h2>Are you sure you want to delete task: <br> "{{ object }}" ?</h2>
            <span class="w-50 m-auto d-flex justify-content-around">
                <input class="btn btn-danger" type="submit" value="Confirm">
                <a class="btn btn-dark" href="{% url 'desk:project_list' %}">Cancel</a>
            </span>
        </form>
    </div>

{% endblock content %}

ToDo/desk/templates/desk/tz_template.html
{% extends "desk/base.html" %}
{% block content %}
    {% load tz %}
    {% get_current_timezone as TIME_ZONE %}
    <form action="{% url 'desk:set_timezone' %}" method="POST">
        {% csrf_token %}
        <label for="timezone">Time zone:</label>
        <select name="timezone">
            {% for tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Set">
    </form>
{% endblock content %}